### ISSUE TITLE
Can you share diagram of the network used?

### ISSUE THREAD

**Issue by manvirvirk** [Rohit-Kundu/Fuzzy-Rank-Ensemble#3]

**Comment by Rohit-Kundu** [comment]
Please refer to our paper published in Nature- Scientific Reports: [Paper](https://www.nature.com/articles/s41598-021-93783-8#article-info) to get all the details for implementation. The diagram has also been updated in `README.md`

**Comment by manvirvirk** [comment]
Thanks for the revert
